FROM nciwebcomm/dotnet-docker:sdk
ARG version_number
RUN curl -SL https://github.com/NCIOCPL/sitewide-search-api/releases/download/${version_number}/sitewide-search-api-${version_number}.zip --output sitewide-search-api.zip \
    && mkdir -p /usr/share/release \
    && unzip sitewide-search-api.zip  -d /usr/share/release
ENV ASPNETCORE_URLS http://*:5008
EXPOSE 5008
WORKDIR /usr/share/release
ENTRYPOINT ["dotnet", "NCI.OCPL.Api.SiteWideSearch.dll"]
